apiVersion: v1
kind: Service
metadata:
  name: ads-db-service
  labels:
    component: ads
    module: db
spec:
  selector:
    component: ads
    module: db
  ports:
    - name: db-service-port
      protocol: TCP
      port: 5432
      targetPort: ads-db-port